## rules.yaml
briefing =
    LANDCOM 16 HQS.
    PŘÍSNĚ TAJNÉ.
    PRO: POLNÍHO VELITELE A9
    
    GRATULUJEME. OBSAZENÍ TECHNOLOGICKÝCH CENTER ODHALILO PODZEMNÍ PŘÍKAZOVÉ CENTRUM STALINA. NAJDĚTE HO A ZAJISTĚTE STALINA ŽIVÉHO.
