## rules.yaml
briefing =
    LANDCOM 16 HQS.
    PRÍSNE TAJNÉ.
    KOMU: VELITEĽ POLE A9
    
    GRATULUJEME. TECHNICKÉ CENTRÁ ZACHYTÁVAJÚCE ODHALILI ZARIADENIE NA PODZEMNÉ ZBRANE. NA VŠETKY GENERÁTORY ULOŽTE VÝBUŠNÉ NÁBOŽKY. VÝSLEDNÉ EXPOZÍCIE BY MALI ZNIČIŤ ZARIADENIE.
    PRED POUŽITÍM NERVOVÉHO PLYNU VYJDITE.
    
    PRENOS KONČÍ.
