## rules.yaml
briefing = Vplyv GDI v tejto oblasti je nekontrolovateľný. Vytvorte dobre umiestnenú základňu úderov a vyčistite oblasť. Neďaleké mesto môže poskytnúť vhodné miesto pre vašu základňu za predpokladu, že obyvatelia budú "presvedčení" aby sa presťahovali....
