## rules.yaml
briefing = Vliv GDI v této oblasti se vymyká kontrole. Vybudujte dobře umístěnou údernou základnu a vyčistěte oblast. Nedaleké město by mohlo poskytnout vhodné místo pro vaši základnu, za předpokladu, že obyvatelé budou „přesvědčeni“ k přestěhování...
