## rules.yaml
briefing =
    LANDCOM 16 HQS.
    PŘÍSNĚ TAJNÉ.
    PRO: POLNÍHO VELITELE A9
    
    ZACHYCENÍ SOVĚTSKÉ KOMUNIKACE NAZNAČUJE, ŽE JEJICH PROJEKT ŽELEZNÁ OPONA SE PŘESUNUL DO TOHOTO SEKTORU. NAJDĚTE A ZNIČTE VEŠKERÉ TECHNOLOGICKÉ STRUKTURY V TOMTO SEKTORU.
