## rules.yaml
briefing =
    LANDCOM 16 HQS.
    PRÍSNE TAJNÉ.
    KOMU: VELITEĽ POLE A9
    
    ZAPOJENIE SOVIETSKEJ KOMUNIKÁCIE NAZNAČUJE, ŽE ICH VÝSKUM ŽELEZNEJ OPONY BOL ZASTAVENÝ ŠPIONÁŽOU. VÝBORNÁ PRÁCA, VELITEĽ!
    
    COMMUNIQUE BOL VYSLEDOVANÝ SPÄŤ K TAJNEJ SOVIETNEJ ZÁKLADNE V BORNHOLM. PRESKÚMAŤ MOŽNÚ SÚVISLOSŤ S VÝSKUMOM ŽELEZNÝCH OPONOV. ZACHYTITE CENTRUM RADARU A ZNIČTE SCHOPNOSTI SUBPRODUKCIE.
    
    POTVRDZOVACÍ KÓD 1138.
    
    PRENOS KONČÍ.
