hotkey-context =
    .player = Hráč
    .spectator = Divák
    .chat-input = Vstup chatu
    .menu = Nabídka
    .editor = Editor

## chat.yaml
hotkey-description-openteamchat = Otevřít týmový chat
hotkey-description-opengeneralchat = Otevřít obecný chat
hotkey-description-togglechatmode = Přepnout režim chatu
hotkey-description-autocomplete = Automatické doplnění

## control-groups.yaml
hotkey-description-controlgroupselect01 = Vybrat skupinu 1
hotkey-description-controlgroupselect02 = Vybrat skupinu 2
hotkey-description-controlgroupselect03 = Vybrat skupinu 3
hotkey-description-controlgroupselect04 = Vybrat skupinu 4
hotkey-description-controlgroupselect05 = Vybrat skupinu 5
hotkey-description-controlgroupselect06 = Vybrat skupinu 6
hotkey-description-controlgroupselect07 = Vybrat skupinu 7
hotkey-description-controlgroupselect08 = Vybrat skupinu 8
hotkey-description-controlgroupselect09 = Vybrat skupinu 9
hotkey-description-controlgroupselect10 = Vybrat skupinu 0
hotkey-description-controlgroupcreate01 = Vytvořit skupinu 1
hotkey-description-controlgroupcreate02 = Vytvořit skupinu 2
hotkey-description-controlgroupcreate03 = Vytvořit skupinu 3
hotkey-description-controlgroupcreate04 = Vytvořit skupinu 4
hotkey-description-controlgroupcreate05 = Vytvořit skupinu 5
hotkey-description-controlgroupcreate06 = Vytvořit skupinu 6
hotkey-description-controlgroupcreate07 = Vytvořit skupinu 7
hotkey-description-controlgroupcreate08 = Vytvořit skupinu 8
hotkey-description-controlgroupcreate09 = Vytvořit skupinu 9
hotkey-description-controlgroupcreate10 = Vytvořit skupinu 0
hotkey-description-controlgroupaddto01 = Přidat do skupiny 1
hotkey-description-controlgroupaddto02 = Přidat do skupiny 2
hotkey-description-controlgroupaddto03 = Přidat do skupiny 3
hotkey-description-controlgroupaddto04 = Přidat do skupiny 4
hotkey-description-controlgroupaddto05 = Přidat do skupiny 5
hotkey-description-controlgroupaddto06 = Přidat do skupiny 6
hotkey-description-controlgroupaddto07 = Přidat do skupiny 7
hotkey-description-controlgroupaddto08 = Přidat do skupiny 8
hotkey-description-controlgroupaddto09 = Přidat do skupiny 9
hotkey-description-controlgroupaddto10 = Přidat do skupiny 0
hotkey-description-controlgroupcombinewith01 = Spojit se skupinou 1
hotkey-description-controlgroupcombinewith02 = Spojit se skupinou 2
hotkey-description-controlgroupcombinewith03 = Spojit se skupinou 3
hotkey-description-controlgroupcombinewith04 = Spojit se skupinou 4
hotkey-description-controlgroupcombinewith05 = Spojit se skupinou 5
hotkey-description-controlgroupcombinewith06 = Spojit se skupinou 6
hotkey-description-controlgroupcombinewith07 = Spojit se skupinou 7
hotkey-description-controlgroupcombinewith08 = Spojit se skupinou 8
hotkey-description-controlgroupcombinewith09 = Spojit se skupinou 9
hotkey-description-controlgroupcombinewith10 = Spojit se skupinou 0
hotkey-description-controlgroupjumpto01 = Přejít na skupinu 1
hotkey-description-controlgroupjumpto02 = Přejít na skupinu 2
hotkey-description-controlgroupjumpto03 = Přejít na skupinu 3
hotkey-description-controlgroupjumpto04 = Přejít na skupinu 4
hotkey-description-controlgroupjumpto05 = Přejít na skupinu 5
hotkey-description-controlgroupjumpto06 = Přejít na skupinu 6
hotkey-description-controlgroupjumpto07 = Přejít na skupinu 7
hotkey-description-controlgroupjumpto08 = Přejít na skupinu 8
hotkey-description-controlgroupjumpto09 = Přejít na skupinu 9
hotkey-description-controlgroupjumpto10 = Přejít na skupinu 0
hotkey-description-removefromcontrolgroup = Odebrat z kontrolní skupiny

## editor.yaml
hotkey-description-editorundo = Zpět
hotkey-description-editorredo = Znovu
hotkey-description-editorcopy = Kopírovat
hotkey-description-editorquicksave = Uložit mapu
hotkey-description-editorpaste = Vložit
hotkey-description-editordeleteselection = Smazat výběr
hotkey-description-editorselecttab = Záložka výběru
hotkey-description-editortilestab = Záložka dlaždic
hotkey-description-editoroverlaystab = Záložka překryvů
hotkey-description-editoractorstab = Záložka aktérů
hotkey-description-editortoolstab = Záložka nástrojů
hotkey-description-editorhistorytab = Záložka historie
hotkey-description-editorsettingstab = Záložka nastavení
hotkey-description-editortogglegridoverlay = Mřížka
hotkey-description-editortogglebuildableoverlay = Stavitelný terén
hotkey-description-editortogglemarkeroverlay = Vrstva značek

## game.yaml
hotkey-description-cyclebase = Přejít na základnu
hotkey-description-tolastevent = Přejít na poslední radarovou událost
hotkey-description-toselection = Přejít na výběr
hotkey-description-selectallunits = Vybrat všechny bojové jednotky
hotkey-description-selectunitsbytype = Vybrat jednotky podle typu
hotkey-description-cycleharvesters = Přepínat harvestery
hotkey-description-pause = Pauza / Pokračovat
hotkey-description-sell = Režim prodeje
hotkey-description-repair = Režim oprav
hotkey-description-placebeacon = Umístit maják
hotkey-description-cyclestatusbars = Přepínat stavové lišty
hotkey-description-togglemute = Přepnout ztlumení zvuku
hotkey-description-toggleplayerstancecolor = Přepnout barvy vztahů
hotkey-description-takescreenshot = Pořídit snímek obrazovky
hotkey-description-attackmove = Útočný pohyb
hotkey-description-stop = Zastavit
hotkey-description-scatter = Rozptýlit se
hotkey-description-deploy = Nasadit
hotkey-description-guard = Strážit
hotkey-description-stanceattackanything = Útočit na vše
hotkey-description-stancedefend = Bránit
hotkey-description-stancereturnfire = Opětovat palbu
hotkey-description-stanceholdfire = Zadržet palbu
hotkey-description-stopmusic = Zastavit
hotkey-description-pausemusic = Pauza nebo pokračování
hotkey-description-prevmusic = Předchozí
hotkey-description-nextmusic = Další

## observer.yaml
hotkey-description-observercombinedview = Všichni hráči
hotkey-description-observerworldview = Vypnout mlhu
hotkey-description-replayspeedslow = Pomalá rychlost
hotkey-description-replayspeedregular = Normální rychlost
hotkey-description-replayspeedfast = Vysoká rychlost
hotkey-description-replayspeedmax = Maximální rychlost
hotkey-description-statisticsnone = Vypnout statistiky
hotkey-description-statisticsbasic = Základní statistiky
hotkey-description-statisticseconomy = Ekonomické statistiky
hotkey-description-statisticsproduction = Produkční statistiky
hotkey-description-statisticssupportpowers = Statistiky podpůrných schopností
hotkey-description-statisticscombat = Bojové statistiky
hotkey-description-statisticsarmy = Statistiky armády
hotkey-description-statisticsgraph = Graf statistik
hotkey-description-statisticsarmygraph = Graf hodnoty armády

## production-common.yaml
hotkey-description-cycleproductionbuildings = Další továrna
hotkey-description-selectproductionbuilding = Aktuální továrna
hotkey-description-production01 = Pozice 01
hotkey-description-production02 = Pozice 02
hotkey-description-production03 = Pozice 03
hotkey-description-production04 = Pozice 04
hotkey-description-production05 = Pozice 05
hotkey-description-production06 = Pozice 06
hotkey-description-production07 = Pozice 07
hotkey-description-production08 = Pozice 08
hotkey-description-production09 = Pozice 09
hotkey-description-production10 = Pozice 10
hotkey-description-production11 = Pozice 11
hotkey-description-production12 = Pozice 12
hotkey-description-production13 = Pozice 13
hotkey-description-production14 = Pozice 14
hotkey-description-production15 = Pozice 15
hotkey-description-production16 = Pozice 16
hotkey-description-production17 = Pozice 17
hotkey-description-production18 = Pozice 18
hotkey-description-production19 = Pozice 19
hotkey-description-production20 = Pozice 20
hotkey-description-production21 = Pozice 21
hotkey-description-production22 = Pozice 22
hotkey-description-production23 = Pozice 23
hotkey-description-production24 = Pozice 24

## supportpowers.yaml
hotkey-description-supportpower01 = Pozice 01
hotkey-description-supportpower02 = Pozice 02
hotkey-description-supportpower03 = Pozice 03
hotkey-description-supportpower04 = Pozice 04
hotkey-description-supportpower05 = Pozice 05
hotkey-description-supportpower06 = Pozice 06

## viewport.yaml
hotkey-description-mapscrollup = Posun nahoru
hotkey-description-mapscrolldown = Posun dolů
hotkey-description-mapscrollleft = Posun vlevo
hotkey-description-mapscrollright = Posun vpravo
hotkey-description-mapjumptotopedge = Přejít na horní okraj
hotkey-description-mapjumptobottomedge = Přejít na dolní okraj
hotkey-description-mapjumptoleftedge = Přejít na levý okraj
hotkey-description-mapjumptorightedge = Přejít na pravý okraj
hotkey-description-mapbookmarksave01 = Uložit záložku 1
hotkey-description-mapbookmarkrestore01 = Přejít na záložku 1
hotkey-description-mapbookmarksave02 = Uložit záložku 2
hotkey-description-mapbookmarkrestore02 = Přejít na záložku 2
hotkey-description-mapbookmarksave03 = Uložit záložku 3
hotkey-description-mapbookmarkrestore03 = Přejít na záložku 3
hotkey-description-mapbookmarksave04 = Uložit záložku 4
hotkey-description-mapbookmarkrestore04 = Přejít na záložku 4
hotkey-description-zoomin = Přiblížit
hotkey-description-zoomout = Oddálit
hotkey-description-resetzoom = Resetovat přiblížení
