## rules.yaml
briefing =
    LANDCOM 16 HQS.
    PRÍSNE TAJNÉ.
    KOMU: VELITEĽ POLE A9
    
    INTELIGENCE RECON UKAZUJE ŤAŽKO
    SOVIETSKE HNUTIE VO VAŠOM OBLASTI.
    MOSTY V OKOLÍ SÚ KĽÚČOVÉ PRE SVIET
    ADVANCEMENT. ZNIČIŤ VŠETKY MOSTY
    ASAP. TANYA POMÔŽE. DRŽTE SI JU
    NAŽIVO ZA KAŽDÚ CENU.
    
    POTVRDZOVACÍ KÓD 1612.
    
    PRENOS KONČÍ.
