## rules.yaml
briefing =
    LANDCOM 16 HQS.
    PŘÍSNĚ TAJNÉ.
    PRO: POLNÍHO VELITELE A9
    
    ZPRAVODAJSKÝ PRŮZKUM UKAZUJE TĚŽKOU SOVĚTSKOU PŘÍTOMNOST V TOMTO SEKTORU. NASAĎTE ZÁKLADNU A ELIMINUJTE VEŠKERÝ SOVĚTSKÝ ODPOR.
