hotkey-context =
    .player = Hráč
    .spectator = Divák
    .chat-input = Vstup chatu
    .menu = Ponuka
    .editor = Redaktor

## chat.yaml
hotkey-description-openteamchat = Otvoriť týmový chat
hotkey-description-opengeneralchat = Otvoriť všeobecný chat
hotkey-description-togglechatmode = Prepnúť režim chatu
hotkey-description-autocomplete = Automatické dopĺňanie

## control-groups.yaml
hotkey-description-controlgroupselect01 = Vybrať skupinu 1
hotkey-description-controlgroupselect02 = Vybrať skupinu 2
hotkey-description-controlgroupselect03 = Vybrať skupinu 3
hotkey-description-controlgroupselect04 = Vybrať skupinu 4
hotkey-description-controlgroupselect05 = Vybrať skupinu 5
hotkey-description-controlgroupselect06 = Vybrať skupinu 6
hotkey-description-controlgroupselect07 = Vybrať skupinu 7
hotkey-description-controlgroupselect08 = Vybrať skupinu 8
hotkey-description-controlgroupselect09 = Vybrať skupinu 9
hotkey-description-controlgroupselect10 = Vybrať skupinu 0
hotkey-description-controlgroupcreate01 = Vytvoriť skupinu 1
hotkey-description-controlgroupcreate02 = Vytvoriť skupinu 2
hotkey-description-controlgroupcreate03 = Vytvoriť skupinu 3
hotkey-description-controlgroupcreate04 = Vytvoriť skupinu 4
hotkey-description-controlgroupcreate05 = Vytvoriť skupinu 5
hotkey-description-controlgroupcreate06 = Vytvoriť skupinu 6
hotkey-description-controlgroupcreate07 = Vytvoriť skupinu 7
hotkey-description-controlgroupcreate08 = Vytvoriť skupinu 8
hotkey-description-controlgroupcreate09 = Vytvoriť skupinu 9
hotkey-description-controlgroupcreate10 = Vytvoriť skupinu 0
hotkey-description-controlgroupaddto01 = Pridať do skupiny 1
hotkey-description-controlgroupaddto02 = Pridať do skupiny 2
hotkey-description-controlgroupaddto03 = Pridať do skupiny 3
hotkey-description-controlgroupaddto04 = Pridať do skupiny 4
hotkey-description-controlgroupaddto05 = Pridať do skupiny 5
hotkey-description-controlgroupaddto06 = Pridať do skupiny 6
hotkey-description-controlgroupaddto07 = Pridať do skupiny 7
hotkey-description-controlgroupaddto08 = Pridať do skupiny 8
hotkey-description-controlgroupaddto09 = Pridať do skupiny 9
hotkey-description-controlgroupaddto10 = Pridať do skupiny 0
hotkey-description-controlgroupcombinewith01 = Spojiť so skupinou 1
hotkey-description-controlgroupcombinewith02 = Spojiť so skupinou 2
hotkey-description-controlgroupcombinewith03 = Spojiť so skupinou 3
hotkey-description-controlgroupcombinewith04 = Spojiť so skupinou 4
hotkey-description-controlgroupcombinewith05 = Spojiť so skupinou 5
hotkey-description-controlgroupcombinewith06 = Spojiť so skupinou 6
hotkey-description-controlgroupcombinewith07 = Spojiť so skupinou 7
hotkey-description-controlgroupcombinewith08 = Spojiť so skupinou 8
hotkey-description-controlgroupcombinewith09 = Spojiť so skupinou 9
hotkey-description-controlgroupcombinewith10 = Spojiť so skupinou 0
hotkey-description-controlgroupjumpto01 = Prejsť na skupinu 1
hotkey-description-controlgroupjumpto02 = Prejsť na skupinu 2
hotkey-description-controlgroupjumpto03 = Prejsť na skupinu 3
hotkey-description-controlgroupjumpto04 = Prejsť na skupinu 4
hotkey-description-controlgroupjumpto05 = Prejsť na skupinu 5
hotkey-description-controlgroupjumpto06 = Prejsť na skupinu 6
hotkey-description-controlgroupjumpto07 = Prejsť na skupinu 7
hotkey-description-controlgroupjumpto08 = Prejsť na skupinu 8
hotkey-description-controlgroupjumpto09 = Prejsť na skupinu 9
hotkey-description-controlgroupjumpto10 = Prejsť na skupinu 0
hotkey-description-removefromcontrolgroup = Odobrať z kontrolnej skupiny

## editor.yaml
hotkey-description-editorundo = Späť
hotkey-description-editorredo = Znovu
hotkey-description-editorcopy = Kopírovať
hotkey-description-editorquicksave = Uložiť mapu
hotkey-description-editorpaste = Vložiť
hotkey-description-editordeleteselection = Zmazať výber
hotkey-description-editorselecttab = Záložka výberu
hotkey-description-editortilestab = Záložka dlaždic
hotkey-description-editoroverlaystab = Záložka prekrytí
hotkey-description-editoractorstab = Záložka aktérov
hotkey-description-editortoolstab = Záložka nástrojov
hotkey-description-editorhistorytab = Záložka histórie
hotkey-description-editorsettingstab = Záložka nastavení
hotkey-description-editortogglegridoverlay = Mriežka
hotkey-description-editortogglebuildableoverlay = Staviteľný terén
hotkey-description-editortogglemarkeroverlay = Vrstva značiek

## game.yaml
hotkey-description-cyclebase = Prejsť na základňu
hotkey-description-tolastevent = Prejsť na poslednú radarovú udalosť
hotkey-description-toselection = Prejsť na výber
hotkey-description-selectallunits = Vybrať všetky bojové jednotky
hotkey-description-selectunitsbytype = Vybrať jednotky podľa typu
hotkey-description-cycleharvesters = Prepínať harvestery
hotkey-description-pause = Pauza / Pokračovať
hotkey-description-sell = Režim predaja
hotkey-description-repair = Režim opráv
hotkey-description-placebeacon = Umiestniť maják
hotkey-description-cyclestatusbars = Prepínať stavové lišty
hotkey-description-togglemute = Prepnúť stlmenie zvuku
hotkey-description-toggleplayerstancecolor = Prepnúť farby vzťahov
hotkey-description-takescreenshot = Vytvoriť snímku obrazovky
hotkey-description-attackmove = Útočný pohyb
hotkey-description-stop = Zastaviť
hotkey-description-scatter = Rozptýliť sa
hotkey-description-deploy = Nasadiť
hotkey-description-guard = Strážiť
hotkey-description-stanceattackanything = Útočiť na všetko
hotkey-description-stancedefend = Brániť
hotkey-description-stancereturnfire = Opätovať paľbu
hotkey-description-stanceholdfire = Zadržať paľbu
hotkey-description-stopmusic = Zastaviť
hotkey-description-pausemusic = Pauza alebo pokračovanie
hotkey-description-prevmusic = Predchádzajúca
hotkey-description-nextmusic = Ďalšia

## observer.yaml
hotkey-description-observercombinedview = Všetci hráči
hotkey-description-observerworldview = Vypnúť hmlu
hotkey-description-replayspeedslow = Pomalá rýchlosť
hotkey-description-replayspeedregular = Normálna rýchlosť
hotkey-description-replayspeedfast = Vysoká rýchlosť
hotkey-description-replayspeedmax = Maximálna rýchlosť
hotkey-description-statisticsnone = Vypnúť štatistiky
hotkey-description-statisticsbasic = Základné štatistiky
hotkey-description-statisticseconomy = Ekonomické štatistiky
hotkey-description-statisticsproduction = Produkčné štatistiky
hotkey-description-statisticssupportpowers = Štatistiky podporných schopností
hotkey-description-statisticscombat = Bojové štatistiky
hotkey-description-statisticsarmy = Štatistiky armády
hotkey-description-statisticsgraph = Graf štatistík
hotkey-description-statisticsarmygraph = Graf hodnoty armády

## production-common.yaml
hotkey-description-cycleproductionbuildings = Ďalšia továrna
hotkey-description-selectproductionbuilding = Aktuálna továreň
hotkey-description-production01 = Slot 01
hotkey-description-production02 = Slot 02
hotkey-description-production03 = Slot 03
hotkey-description-production04 = Slot 04
hotkey-description-production05 = Slot 05
hotkey-description-production06 = Slot 06
hotkey-description-production07 = Slot 07
hotkey-description-production08 = Slot 08
hotkey-description-production09 = Slot 09
hotkey-description-production10 = Slot 10
hotkey-description-production11 = Slot 11
hotkey-description-production12 = Slot 12
hotkey-description-production13 = Slot 13
hotkey-description-production14 = Slot 14
hotkey-description-production15 = Slot 15
hotkey-description-production16 = Slot 16
hotkey-description-production17 = Slot 17
hotkey-description-production18 = Slot 18
hotkey-description-production19 = Slot 19
hotkey-description-production20 = Slot 20
hotkey-description-production21 = Slot 21
hotkey-description-production22 = Slot 22
hotkey-description-production23 = Slot 23
hotkey-description-production24 = Slot 24

## supportpowers.yaml
hotkey-description-supportpower01 = Slot 01
hotkey-description-supportpower02 = Slot 02
hotkey-description-supportpower03 = Slot 03
hotkey-description-supportpower04 = Slot 04
hotkey-description-supportpower05 = Slot 05
hotkey-description-supportpower06 = Slot 06

## viewport.yaml
hotkey-description-mapscrollup = Posun nahor
hotkey-description-mapscrolldown = Posun nadol
hotkey-description-mapscrollleft = Posun vľavo
hotkey-description-mapscrollright = Posun vpravo
hotkey-description-mapjumptotopedge = Prejsť na horný okraj
hotkey-description-mapjumptobottomedge = Prejsť na dolný okraj
hotkey-description-mapjumptoleftedge = Prejsť na ľavý okraj
hotkey-description-mapjumptorightedge = Prejsť na pravý okraj
hotkey-description-mapbookmarksave01 = Uložiť záložku 1
hotkey-description-mapbookmarkrestore01 = Prejsť na záložku 1
hotkey-description-mapbookmarksave02 = Uložiť záložku 2
hotkey-description-mapbookmarkrestore02 = Prejsť na záložku 2
hotkey-description-mapbookmarksave03 = Uložiť záložku 3
hotkey-description-mapbookmarkrestore03 = Prejsť na záložku 3
hotkey-description-mapbookmarksave04 = Uložiť záložku 4
hotkey-description-mapbookmarkrestore04 = Prejsť na záložku 4
hotkey-description-zoomin = Priblížiť
hotkey-description-zoomout = Oddialiť
hotkey-description-resetzoom = Resetovať priblíženie
